shadow = true;
shadow-radius = 12;
shadow-offset-x = -7;
shadow-offset-y = -7;

fading = true;
fade-in-step = 0.05;
fade-out-step = 0.05;

corner-radius = 10;
round-borders = 1;

blur: {
  method = "dual_kawase";
  strength = 5;
};

backend = "glx";
vsync = true;
detect-rounded-corners = true;
detect-client-opacity = true;
detect-transient = true;
log-level = "warn";

rules = (
    {
        match = "ANY";
        shadow = true;
        fade = true;
        blur-background = true;
        corner-radius = 10;
        opacity = 1.0;
        inactive-opacity = 1.0;
        inactive-dim = 0.0;
    },
    {
        match = "class_g = 'flameshot' || "
                "class_g = 'Rofi' || "
                "window_type = 'dock' || "
                "window_type = 'desktop'";
        shadow = false;
        fade = false;
        blur-background = false;
        corner-radius = 0;
    },
    { match = "class_g = 'i3bar'"; opacity = 0.85; },
    { match = "class_g = 'discord' || class_g = 'vesktop'"; opacity = 0.95; },
    { match = "class_g = 'Rofi'"; opacity = 0.8; },
    { match = "name = 'Zed'"; opacity = 0.85; },
    { match = "class_g = 'Kitty'"; opacity = 0.95; },
    { match = "class_i = 'spotify'"; opacity = 0.8; }
);

animations = (
  {
    triggers = ["open", "show"];
    opacity = {
      curve = "cubic-bezier(0,1,1,1)";
      duration = 0.3;
      start = 0;
      end = "window-raw-opacity";
    };
    scale-x = {
      curve = "cubic-bezier(0,1.3,1,1)";
      duration = 0.3;
      start = 0.8;
      end = 1;
    };
    scale-y = "scale-x";
  },
  {
    triggers = ["close", "hide"];
    opacity = {
      curve = "linear";
      duration = 0.2;
      start = "window-raw-opacity-before";
      end = 0;
    };
  }
);
