[redshift]
temp-day=6500
temp-night=2000

fade=0

dawn-time=4:00-6:15
dusk-time=20:35-23:59

brightness-day=1
brightness-night=0.9
gamma=1

location-provider=manual

adjustment-method=randr

[manual]
lat=38.9
lon=-77.0

[randr]
